{% set name = "xicam" %}
{% set version = "2.2.5" %}
{% set sha256 = "e62c09bf3924e7f319795ffb4111bc4ae16324981dcbf7fcc235deb8363c687c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Xi-CAM/Xi-cam/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]
  entry_points:
    - xicam=run_xicam:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - area-detector-handlers
    - astropy
    - databroker >=1.0.0b5
    - event-model >=1.13.0b4
    - numpy
    - pyqt >=5
    - qdarkstyle
    - qtmodern
    - qtpy
    - signalslot
    - xicam.core
    - xicam.gui
    - xicam.plugins 
    - yapsy

test:
  imports:
    - xicam
    - xicam.args

about:
  home: https://xi-cam.readthedocs.io
  license: BSD 3-clause
  license_file: LICENSE.md
  summary: An extensible platform for synchrotron data reduction, visualization, and management
  dev_url: https://github.com/Xi-CAM/Xi-cam
  doc_url: https://xi-cam.readthedocs.io
